# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Institute.create(code: 'NITC', name: 'National Institute of Technology, Calicut')
Institute.create(code: 'NITJ', name: 'Dr. B.R. Ambedkar National Institute of Technology Jalandhar')
Institute.create(code: 'MNIT', name: 'Malaviya National Institute of Technology,Jaipur')
Institute.create(code: 'MANIT', name: 'Maulana Azad National Institute of Technology, Bhopal')
Institute.create(code: 'MNNIT', name: 'Motilal Nehru National Institute of Technology, Allahabad')
Institute.create(code: 'NITA', name: 'National Institute of Technology Agartala')
Institute.create(code: 'NITD', name: 'National Institute of Technology Delhi')
Institute.create(code: 'NITDGP', name: 'National Institute of Technology Durgapur')
Institute.create(code: 'NITG', name: 'National Institute of Technology Goa')
Institute.create(code: 'NITH', name: 'National Institute of Technology Hamirpur')
Institute.create(code: 'NITK', name: 'National Institute of Technology Karnataka Surathkal')
Institute.create(code: 'NITM', name: 'National Institute of Technology Meghalaya')
Institute.create(code: 'NITN', name: 'National Institute of Technology Nagaland')
Institute.create(code: 'NITP', name: 'National Institute of Technology Patna')
Institute.create(code: 'NITPY', name: 'National Institute of Technology Puducherry')
Institute.create(code: 'NITRR', name: 'National Institute of Technology, Raipur')
Institute.create(code: 'NITSKM', name: 'National Institute of Technology Sikkim')
Institute.create(code: 'NITAP', name: 'National Institute of Technology, Arunachal Pradesh')
Institute.create(code: 'NITJSR', name: 'National Institute of Technology Jamshedpur')
Institute.create(code: 'NITKKR', name: 'National Institute of Technology Kurukshetra')
Institute.create(code: 'NITMN', name: 'National Institute of Technology Manipur')
Institute.create(code: 'NITRKL', name: 'National Institute of Technology Rourkela')
Institute.create(code: 'NITS', name: 'National Institute of Technology Silchar')
Institute.create(code: 'NITSRI', name: 'National Institute of Technology Srinagar')
Institute.create(code: 'NITT', name: 'National Institute of Technology Tiruchirappalli')
Institute.create(code: 'NITW', name: 'National Institute of Technology, Warangal')
Institute.create(code: 'SVNIT', name: 'Sardar Vallabhbhai National Institute of Technology, Surat')
Institute.create(code: 'VNIT', name: 'Visvesvaraya National Institute of Technology, Nagpur')
Institute.create(code: 'NITUK', name: 'National Institute of Technology, Uttarakhand')
Institute.create(code: 'NITMZ', name: 'National Institute of Technology Mizoram')
Institute.create(code: 'NITANP', name: 'NIT Andhra Pradesh')

User.create(name: 'siteadmin', username: 'siteadmin', email: 'siteadmin@nitc.ac.in', password: '123456',  role: 'SiteAdmin', contactno: '8281459634')
